### ISSUE TITLE
OPML Support?

### ISSUE THREAD

**Issue by ckolos** [Lallassu/gorss#1]
I have an extensive collection of feeds in a different reader. Any plans to add OPML import support?

**Comment by Lallassu** [comment]
This seems pretty simple to add. I'll take a look at it.

**Comment by Lallassu** [comment]
The latest in master branch now supports to load OPML files. Point out the file in `gorss.conf` using the "opmlFile" configuration directive (see the README.md for example).

It will read the OMPL and fetch the URLs. I've just tested it using a standard generated OPML file with a couple of URLs.
