### ISSUE TITLE
[feature request] Non blocking feed update

### ISSUE THREAD

**Issue by aearil** [Lallassu/gorss#10]
First of all, thank you for developing this awesome looking tool! :)

That said I have one issue that's preventing me from switching to gorss as my daily driver: right now, when you update the feeds, gorss's UI freezes until all the feeds have been updated. This is particularly noticeable at startup, and I can only guess that the problem is going to get worse as I add more feeds.

I think it would be nice to have the feeds update in a background thread so that the rest of the UI can feel snappy at all time.

I'm sorry I have no code to show for it as I lack experience writing in Go

**Comment by Lallassu** [comment]
Sounds like a good thing to fix. I add that to my todo list :)

**Comment by Lallassu** [comment]
I just realised that I did try to do this earlier. The reason for not doing it was that the UI library tview was not working easily concurrent. Need to look into this in more depth.

**Comment by aearil** [comment]
Ok, thank you for taking the time to look into it.

From the little I understood while reading about tview, widgets (apart
from TextView) don't like to be updated from a coroutine (though it is
possible). That said, it should be possible to update feeds in the
background and then getting the result back to the main thread in
order to update the UI, or am I mistaken on how tview and gorss work ?

**Comment by Oppen** [comment]
Related to this, it would be good to download the feeds concurrently. Thanks to how the Go runtime works, this should require just firing up goroutines where now a sequential download is done.
