### ISSUE TITLE
Clean up downloading errors

### ISSUE THREAD

**Issue by Donearm** [Lallassu/gorss#12]
I hope the screenshot is explicative enough of the issue, but how do I clear the screen of rss urls printing errors to stdout? I am using Archlinux with kitty terminal

![image](https://user-images.githubusercontent.com/120833/79635643-5b863b80-8172-11ea-8bd7-56f5c15d1dbd.png)

**Comment by Donearm** [comment]
Besides, I've changed `log.Printf` to `fmt.Errorf` in rss.go at line 65 and am testing it. No error message is showing as of now on the screen so it could be solved just with this. I don't know if you're fine with not having such messages going to log

**Comment by Donearm** [comment]
So far no errors showing on screen after this [commit](https://github.com/Donearm/gorss/commit/bfb996de8056349f78375c9d9b965c8e5dec3414). I'll continue testing.

**Comment by Lallassu** [comment]
Yes, it's the logging that writes to stdout. I will create a fix for this where I write all logs to file instead. That way no errors will turn up in the UI. Because there can be other errors as well.

**Comment by Lallassu** [comment]
Fix here: https://github.com/Lallassu/gorss/commit/e374ffe1862182264db16b042169d23864774410
