### ISSUE TITLE
Article highlighted is the index from the previous feed

### ISSUE THREAD

**Issue by shaneHowearth** [Lallassu/gorss#16]
I've discovered that when I move from one feed to another the highlighting of the Article is set to the index that it was in the last feed,. this is odd when moving between feeds, but not a deal breaker, except when you move to a feed with a limited count of articles.

eg. I was looking at articles in my Hacker News Feed (which has 1081 articles in it), and I was at index 40+. I moved to my Go-time podcasts feed, which has 2 articles in it, and I couldn't move to either of them, because the index is set to.. 40 odd from the previous feed win.

I'd like to have the index set smarter, to the most recent unread article?

**Comment by Lallassu** [comment]
Sounds like a bug indeed.
