### ISSUE TITLE
Proposal: Ask before exit

### ISSUE THREAD

**Issue by shaneHowearth** [Lallassu/gorss#18]
As a Vim user I habitually hit the `Esc` key before I go to do something that my mind thinks should be in command mode (i know, I know). Unfortunately this key is set to 'exit' Gorss. 

I have no desire to change the key, but I do wish that the application would ask me if I want to exit.

**Comment by Lallassu** [comment]
I'm also a vim user and totally get what you mean, so it sounds like a good addition :+1:
