### ISSUE TITLE
make all shouldn't depend on the `clean` target

### ISSUE THREAD

**Issue by aearil** [Lallassu/gorss#23]
Right now, when you call `make`, the build environment spends a few minutes chugging along, compiling everything, and in the end you're left back where you started because all the build artefacts were removed by the `clean` target.

Usually, one expects that calling `make` will at least result in a usable binary, something like `make build` in your makefile.

In the **Makefile**, I would replace `all: build release clean` by `all: build`.

**Comment by Lallassu** [comment]
Good catch, I didn't see that myself, usually run `make run` and then `make release`.

Thanks, fixed!
