### ISSUE TITLE
add support for LSB ~/.config

### ISSUE THREAD

**Issue by r3k2** [Lallassu/gorss#33]
Hello I love the app, I wanted a CLI go RSS reader that will auto-update, so I can just have it there showing me the news.
But, I think it only supports old UNIX and BSD standard ~/.myconfig instead of nowadays modern LSB (Linux standard base) ~/.config/nameofsoftware/config

I usually will just dive myself in a fork but I am 100% full of work and I attempt to avoid github for coding as much as possible I tend to help projects on gitlab, sourcehut and such.

**Comment by Lallassu** [comment]
Maybe as a workaround for now, you could use the flag `-config <path_to_conf>` and have your configuration in `~/.config/gorss/`.

**Comment by r3k2** [comment]
Yap this is what I am doing, but is only a workaround, every Linux application should  follow and standard so other apps, can know its existence, if I want to move the app to /usr/local/bin/ and its config etc. it should be ready for that, so I can package it etc later on.

**Comment by pradyumnac** [comment]
isnt this fixed now?

**Comment by Lallassu** [comment]
I think so yes, if not please re-open.
